[package]
name = "project-dash"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.48.0", features = ["full"] }
ratatui = "0.29.0"
crossterm = { version = "0.29", features = ["event-stream"] }
color-eyre = "0.6.5"
futures = "0.3.31"
